image: maven:3.3.9

pipelines:
  default:
    - step:
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - cd epubmergelib && mvn -B verify # -B batch mode makes Maven less verbose
